### ISSUE TITLE
Complete the DM's REST client

### ISSUE THREAD

**Issue by vincent-zurczak** [roboconf/roboconf-platform#129]
Add support for the following operations:
* resynchronize
* remove instance

**Comment by bourretp** [comment]
It seems these operations are *already implemented* since September 2014 (9af91d16f34efdab4b15c4aa035b961dfb300687) in `net.roboconf.dm.rest.services.internal.resources.ApplicationResource` **and** `net.roboconf.dm.management.Manager` classes. The issue #121 is related to the following code. Is this issue a duplicate, or something completely different?

Small code extract
```java
public class ApplicationResource implements IApplicationResource {

	// …

	@Override
	public Response removeInstance( String applicationName, String instancePath ) {
		// …
		this.manager.removeInstance( ma, instance );
		// …
	}

	// …
	
	@Override
	public Response resynchronize( String applicationName ) {
		// …
		this.manager.resynchronizeAgents( ma );
		// …
	}

	// …

}
```

**Comment by vincent-zurczak** [comment]
The mentionned code is about the server side of the REST API.
This issue is about completing the REST **client**.

**Comment by bourretp** [comment]
Ok, my bad!
Starting on it...
