### ISSUE TITLE
Templating: provide a way to delete reports that correspond to undeployed resources

### ISSUE THREAD

**Issue by gibello** [roboconf/roboconf-platform#305]
When a resource is deployed (and then, everytime its state changes), a report is created.
When the resource is undeployed, there is no way to delete the report.
Note that the problem may be more general: it could be suitable to delete a report upon any state change (eg. a user might need to delete some reports when a resource is stopped).
So we should find a way to trigger actions upon state changes (lifecycle scripts ?)

**Comment by vincent-zurczak** [comment]
Normally, reports are generated every time the DM saves the current state.
And this is performed every time an instance state changes.

**Comment by vincent-zurczak** [comment]
I am not sure this issue makes sense.
Since my last commit, when an application is deleted, generated files for this application are all deleted. However, the issue allows to think this might apply to deleted instances.

It cannot.
Templates are associated with applications. When an instance changes, all the generated files for the application are updated. If no instance matches the template criteria, it will most likely produce an empty file (in fact, it depends on the template's content). The only thing we could do is to delete / not write empty generated files.

WDYT?

**Comment by vincent-zurczak** [comment]
Up! WDYT about my last message?

**Comment by bourretp** [comment]
For me it doesn't really make sense too.
The template language was initially intended to produce *intermediate* reports... Those reports are then processed externally in order to (e.g.) make coffee. Choosing a web-template language like Mustache, is OK, as soon as we only need to write formatted data... 

But recently the Roboconf reporting facility has been extended with several features that let me think it will sooner or later, and by itself, suppress line breaks, evaluate complex conditions, remove empty reports, send an e-mail to the fire fighters, and of course make coffee (in a Turing complete way).

I personally think that the simpler is the better. For sure the templating engine will need some new fixtures before becoming fully usable. But complex data handling should be performed on the "coffee-maker" side, not the template formatting one.

More seriously and illustratively, if a application/component//instance/whatever is gone, the updated report should provide enough info to detect it, and, on the coffee-maker side, perform appropriated actions. Relying on the presence/absence of a report is, imoo, buggy, dangerous, superfluous, redundant, bloatware, and against my own perception of any decoupled component-based coffeemaker ;)

:-1:

**Comment by vincent-zurczak** [comment]
You are right, the templating spirit changed a little bit since the original specification.

I suggest we keep things the way they are.
Said differently with an example, if there is no root instance, either the template outputs something to tell it, or it is done such a way the file will be empty.
