### ISSUE TITLE
Messaging in agent is never configured on IaaS VMs (user-data not propagated)

### ISSUE THREAD

**Issue by gibello** [roboconf/roboconf-platform#360]
When the DM deploys a new VM on a IaaS (eg. EC2), it passes configuration information across user-data. These informations should be used to configure the agent's messaging... but they are not, and the messaging points to localhost (default) although the user-data are properly updated (on EC2, can be checked by browsing http://169.254.169.254/latest/user-data on the VM).
As a consequence, the VM never gets in deployed/started state on the DM side (and remains "being deployed" forever), because no message arrives.

**Comment by vincent-zurczak** [comment]
I thought about it...

I explored 3 ideas.

1 - Inject the config admin service in the agent.
When it finds user data, it would update the configuration of the messaging bundle.

Pros: the messaging is configured.
Cons: @bourretp said it might not work (for security reasons, not anyone can modify the configuration of other bundles). Besides, we don't always know which messaging bundle has to be updated.

2 - Add a new script in the distribution.
When we install an agent on a IaaS VM, we already edit the agent's configuration to indicate we use this or that IaaS. We could have changed this and require to update or set a script that would get the user data and update the configuration. However, user data are not retrieved from the same location in all the IaaS. EC2 is similar to Openstack (same URL), but Azure uses another way. This solution would be very hard to implement.

3 - Let the agent updates the configuration **file** of the messaging directly.
It appears to be possible. When we run a bundle, we can access Karaf's variables, including the KARAF_ETC directory. So, here is a suggestion...

We add a new method in [UserDataUtils](https://github.com/roboconf/roboconf-platform/blob/master/core/roboconf-agent/src/main/java/net/roboconf/agent/internal/misc/UserDataUtils.java).

```java
public static void updateMessagingConfiguration( Map<String,String> msgData, String messagingType ) {

     String etcDir = System.getProperty( "karaf.etc" );
     if( ! Utils.isEmptyOrWhiteSpaces( etcDir )) {

           // Find the *.cfg file that starts with "net.roboconf.messaging."
           // .... and that contains messagingType (e.g. rabbitmq).
           // Update its content. Messaging clients are now configured independently of the agent / DM).
     } else {
           // Log something
     }
}
```

We won't be able to add unit tests about it.
This is because they don't run in Karaf. However, we should an integration test about it.
BTW, I made the test, we really get Karaf's ETC directory with ```System.getProperty( "karaf.etc" )```.

**Comment by vincent-zurczak** [comment]
Rewriting the Karaf configuration will work.
But we can also consider another solution.

We could update the reconfigurable client.
We add a method to pass user data. When new user data are passed, the reconfigurable client switches to a new messaging client.

This solution is cleaner because it only relies on internal mechanisms. But it will take at least a day to implement and test.

Concrete messaging implementations will invoke ReconfigurableClient.getUserData() to extract additional configuration. Notice we should not call it user data, since it is a IaaS thing. In the scope of the messaging, we can call it **forcedConfiguration**, i.e. a configuration that overrides the one given by ConfigAdmin.

**Comment by vincent-zurczak** [comment]
A week-end later, I think the first option is the best.
We should assume OSGi's config admin is the only option to configure the agent in an OSGi environment. What I did not like in the user data management, was that sometimes, we kept the user admin configuration. And sometimes, we overrode it with user data.

In the start method of the agent, we should read user data and write them into the right configuration files. And in the same time, we should simply the code of the **reconfigure** method. This is the best option.

When we are outside an OSGi environment, **karaf.etc** will not be defined and thus, we won't use user data. This is fine in the sense where we have to configure manually the messaging clients in such a case (it is what we do with unit tests).

**Comment by gibello** [comment]
Just tested on EC2, starting from a image where the messaging IP & 
credentials have been updated manually.

Works fine... so the problem is exactly what we guessed (and is only 
related to the messaging).

I would vote for option 3 (config file overwrite). Easy to code, and to 
understand.

**Comment by vincent-zurczak** [comment]
> I would vote for option 3 (config file overwrite). Easy to code, and to understand.

Yes. And nice for debug and support.

**Comment by vincent-zurczak** [comment]
Verified on EC2.
The mechanism works again. :+1:
