### ISSUE TITLE
Target Docker embeds many dependencies, probably too many...

### ISSUE THREAD

**Issue by bourretp** [roboconf/roboconf-platform#378]
The latest `roboconf-target-docker` bundle is very heavy (~12MB). Despite this is not a problem itself, I've opened and I've seen that it embeds the SLF4J api (`org.slf4j` package). This cause a warning since the embedded SLF4J cannot find any logger implementation. The package should be imported, as the other bundles do.

Maybe some of the other dependencies could be imported too, instead of being embedded.

The jar is fat, let's start a diet! :tropical_drink:

**Comment by vincent-zurczak** [comment]
It seems this diet is responsible of #402.
Besides, I notice it was not very efficient because the JAR is still 11 MB. One of the advantage we saw in OSGi was that we could make various handlers coexist while they use different versions of Jersey.

I suggest we partially revert some of these changes, in particular about Jersey and Jackson.
