### ISSUE TITLE
Add capability to interrupt a frozen lifecycle change

### ISSUE THREAD

**Issue by cdeneux** [roboconf/roboconf-platform#604]
I'm using ``apt-get install`` to deploy Cacti through the plugin Script. Some information are asked to the user during the installation process. I use ``debconf-set-selections`` to transmit these expected values to ``apt-get``.
But if for any reasons a value is not transmitted, ``apt-get install`` is frozen asking indefinitely the missing information. And so, all the Roboconf agent is blocked.

Please provide a way to interrupt such situation, for example using a timeout or an administration command available in the web-console.

**Comment by vincent-zurczak** [comment]
Indeed, if a recipe remains stuck, the agent will never respond then.
We need to add a new message type that once received by an agent, interrupts the current execution. This may imply updating the target API.

Then, we will need an update of our REST API so that a user can run it.
Or maybe we only need a new Karaf command to execute on an agent, rather than a « remote » solution.

**Comment by vincent-zurczak** [comment]
Having a message that interrupts sub-processes is very complicated.
I don't want to explore more this option.

Having a timeout on execution may be another option.
But this would raise other issues (e.g. what about situations when the internet connection is slow).

I think the most simple solution is to provide a Karaf command.
When an agent is stuck, users would connect to the remote agent (e.g. through SSH), log into Karaf's shell and execute something like `roboconf:recipe-execution cancel`.

We could also have another command to get the output of the current recipe with `roboconf:recipe-execution status`.

@cdeneux, is this acceptable for you?
